---
title: "A Bayerisch Disco Flight"
author: "Alex Dolphin"
date: 2020-06-07T09:04:00+01:00
categories: ["R"]
tags: ["drone"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, echo = FALSE)
```

In my brief visit to the South of Germany I did a second drone flight in the
area of Neuschwanstein Castle.

Without too much history
[the castle](https://goo.gl/maps/FHMN3t3zmZHh5DKq5)
was built in the late 1800s on a rugged
hill near the Austrian border in Bavarian Germany. It's quite a popular tourist
landmark given that it's a very picturesque region set just before the Alps,
and has an almost Disney-style appearance.

The castle was closed due to Coronavirus, so I thought it was a good opportunity
to fly the drone without the risk of large numbers of people around. I couldn't
fly too close to the castle due to the nature of the landscape and just respect
for the local farmland, but nevertheless I got some nice video footage as you
can see below:

<center>
<iframe width="560" height="315" src="https://www.youtube.com/embed/eu_p0xkGD0Y" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</center>

As the weather was great and there is so much beautiful landscape around the
area I decided to do a quick second flight next to
[Forggensee](https://goo.gl/maps/JpMtRL6u4KQnWCKu9),
a large lake nearby with a spectacular turquoise colour.

<center>
<iframe width="560" height="315" src="https://www.youtube.com/embed/IHSLgd4pz8I" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</center>